import type { FastifyReply, FastifyRequest } from "fastify";
import type {
  AppLoadContext,
  RouterContextProvider,
  UNSAFE_MiddlewareEnabled as MiddlewareEnabled,
} from "react-router";

type MaybePromise<T> = T | Promise<T>;

/**
 * A function that returns the value to use as `context` in route `loader` and
 * `action` functions.
 *
 * You can think of this as an escape hatch that allows you to pass
 * environment/platform-specific values through to your loader/action, such as
 * values that are generated by Fastify middleware like `request.session`.
 */
type GetLoadContextFunction = (
  request: FastifyRequest,
  reply: FastifyReply,
) => MiddlewareEnabled extends true
  ? MaybePromise<RouterContextProvider>
  : MaybePromise<AppLoadContext>;

export type { GetLoadContextFunction };
