import { TIMING_IN_MS as SHARED_TIMING_IN_MS } from "@shared/constants/timing.constant";

const {
  SECONDS_FIVE,
  SECONDS_ONE,
  SECONDS_ONE_HALF,
  SECONDS_ONE_TENTH,
  SECONDS_TEN,
  SECONDS_THREE,
  SECONDS_TWO,
} = SHARED_TIMING_IN_MS;

const TIMING_IN_MS = Object.freeze({
  COOPERATIVE_HANDOVER_TIMEOUT: SECONDS_TEN + SECONDS_FIVE + SECONDS_ONE,
  FORCE_SHUTDOWN_TIMEOUT: SECONDS_THREE,
  GRACEFUL_SHUTDOWN_TIMEOUT: SECONDS_TEN + SECONDS_FIVE,
  LISTEN_POLL_INITIAL_INTERVAL: SECONDS_ONE_TENTH,
  LISTEN_POLL_MAX_INTERVAL: SECONDS_ONE_HALF,
  SHUTDOWN_REQUEST_TIMEOUT: SECONDS_TWO,
} as const);

export { TIMING_IN_MS };
