const TIMING = Object.freeze({
  SECONDS_FIVE_IN_MS: 5_000,
  SECONDS_ONE_TENTH_IN_MS: 100,
  SECONDS_TEN_IN_MS: 10_000,
  SECONDS_THREE_IN_MS: 3_000,
  SECONDS_TWO_IN_MS: 2_000,
} as const);

export { TIMING };
