import {
  createReadableStreamFromReadable,
  writeReadableStreamToWritable,
} from "@react-router/node";
import type {
  FastifyPluginCallback,
  FastifyReply,
  FastifyRequest,
} from "fastify";
import type {
  AppLoadContext,
  RouterContextProvider,
  ServerBuild,
  UNSAFE_MiddlewareEnabled as MiddlewareEnabled,
} from "react-router";
import { createRequestHandler as createRemixRequestHandler } from "react-router";

type MaybePromise<T> = T | Promise<T>;

/**
 * A function that returns the value to use as `context` in route `loader` and
 * `action` functions.
 *
 * You can think of this as an escape hatch that allows you to pass
 * environment/platform-specific values through to your loader/action, such as
 * values that are generated by Fastify middleware like `req.session`.
 */
export type GetLoadContextFunction = (
  req: FastifyRequest,
  res: FastifyReply
) => MiddlewareEnabled extends true
  ? MaybePromise<RouterContextProvider>
  : MaybePromise<AppLoadContext>;

export const createRemixHeaders = (
  requestHeaders: FastifyRequest["headers"]
): Headers => {
  const headers = new Headers();

  for (const [key, values] of Object.entries(requestHeaders)) {
    if (values) {
      if (Array.isArray(values)) {
        for (const value of values) {
          headers.append(key, value);
        }
      } else {
        headers.set(key, values);
      }
    }
  }

  return headers;
};

export const createRemixRequest = (
  req: FastifyRequest,
  res: FastifyReply
): Request => {
  // req.hostname doesn't include port information so grab that from
  // `X-Forwarded-Host` or `Host`
  const xForwardedHost = req.headers["x-forwarded-host"];
  const host = req.headers.host;
  const xForwardedHostStr = Array.isArray(xForwardedHost)
    ? xForwardedHost[0]
    : xForwardedHost;
  const hostStr = Array.isArray(host) ? host[0] : host;
  const [, hostnamePortStr] = (xForwardedHostStr as string)?.split(":") ?? [];
  const [, hostPortStr] = (hostStr as string)?.split(":") ?? [];
  const hostnamePort = Number.parseInt(hostnamePortStr ?? "", 10);
  const hostPort = Number.parseInt(hostPortStr ?? "", 10);
  const port =
    Number.isSafeInteger(hostnamePort) || Number.isSafeInteger(hostPort)
      ? hostnamePort || hostPort || ""
      : "";
  // Use req.hostname here as it respects the "trust proxy" setting
  const resolvedHost = `${req.hostname}${port ? `:${port}` : ""}`;
  // Use `req.url` so Remix is aware of the full path
  const url = new URL(`${req.protocol}://${resolvedHost}${req.url}`);

  // Abort action/loaders once we can no longer write a response
  let controller: AbortController | null = new AbortController();
  const init: RequestInit = {
    method: req.method,
    headers: createRemixHeaders(req.headers),
    signal: controller.signal,
  };

  // Abort action/loaders once we can no longer write a response iff we have
  // not yet sent a response (i.e., `close` without `finish`)
  // `finish` -> done rendering the response
  // `close` -> response can no longer be written to
  res.raw.on("finish", () => (controller = null));
  res.raw.on("close", () => controller?.abort());

  if (req.method !== "GET" && req.method !== "HEAD") {
    init.body = createReadableStreamFromReadable(req.raw);
    (init as { duplex: "half" }).duplex = "half";
  }

  return new Request(url.href, init);
};

export const sendRemixResponse = async (
  res: FastifyReply,
  nodeResponse: Response
): Promise<void> => {
  res.status(nodeResponse.status);

  for (const [key, value] of nodeResponse.headers.entries()) {
    res.header(key, value);
  }

  if (nodeResponse.headers.get("Content-Type")?.match(/text\/event-stream/i)) {
    res.raw.flushHeaders();
  }

  if (nodeResponse.body) {
    await writeReadableStreamToWritable(nodeResponse.body, res.raw);
  } else {
    res.raw.end();
  }
};

/**
 * Returns a Fastify plugin that serves the response using React Router.
 */
export const createRequestHandler = ({
  build,
  getLoadContext,
  mode = process.env.NODE_ENV,
}: {
  build: ServerBuild | (() => Promise<ServerBuild>);
  getLoadContext?: GetLoadContextFunction;
  mode?: string;
}): FastifyPluginCallback => {
  const handleRequest = createRemixRequestHandler(build, mode);

  return (fastify, _opts, done) => {
    // Register a catch-all route for React Router (but skip static files)
    fastify.all("*", async (req, res) => {
      // Skip static file requests - let Fastify static handle them
      if (req.url.startsWith("/assets/") || req.url.includes(".")) {
        return res.callNotFound();
      }

      // eslint-disable-next-line no-useless-catch
      try {
        const request = createRemixRequest(req, res);
        const loadContext = await getLoadContext?.(req, res);

        const response = await handleRequest(request, loadContext);

        await sendRemixResponse(res, response);
      } catch (error: unknown) {
        // Let Fastify handle the error
        throw error;
      }
    });

    done();
  };
};
