import { TIMING_IN_MS } from "@shared/constants/timing.constant";

const {
  SECONDS_ONE_HALF,
  SECONDS_ONE,
  SECONDS_ONE_TENTH,
  SECONDS_TEN,
  SECONDS_THREE,
  SECONDS_TWO,
} = TIMING_IN_MS;

const TIMING = Object.freeze({
  COOPERATIVE_HANDOVER_TIMEOUT_MS: SECONDS_TEN + SECONDS_ONE,
  FORCE_SHUTDOWN_TIMEOUT_MS: SECONDS_THREE,
  GRACEFUL_SHUTDOWN_TIMEOUT_MS: SECONDS_TEN,
  LISTEN_POLL_INITIAL_INTERVAL_MS: SECONDS_ONE_TENTH,
  LISTEN_POLL_MAX_INTERVAL_MS: SECONDS_ONE_HALF,
  SHUTDOWN_REQUEST_TIMEOUT_MS: SECONDS_TWO,
} as const);

export { TIMING };
