import { TIMING as SHARED_TIMING } from "@shared/constants/timing.constant";

const {
  SECONDS_ONE_HALF_IN_MS,
  SECONDS_ONE_IN_MS,
  SECONDS_ONE_TENTH_IN_MS,
  SECONDS_TEN_IN_MS,
  SECONDS_THREE_IN_MS,
  SECONDS_TWO_IN_MS,
} = SHARED_TIMING;

const TIMING = Object.freeze({
  COOPERATIVE_HANDOVER_TIMEOUT_MS: SECONDS_TEN_IN_MS + SECONDS_ONE_IN_MS,
  FORCE_SHUTDOWN_TIMEOUT_MS: SECONDS_THREE_IN_MS,
  GRACEFUL_SHUTDOWN_TIMEOUT_MS: SECONDS_TEN_IN_MS,
  LISTEN_POLL_INITIAL_INTERVAL_MS: SECONDS_ONE_TENTH_IN_MS,
  LISTEN_POLL_MAX_INTERVAL_MS: SECONDS_ONE_HALF_IN_MS,
  SHUTDOWN_REQUEST_TIMEOUT_MS: SECONDS_TWO_IN_MS,
} as const);

export { TIMING };
